@baseUrl = http://localhost:3000
@json = application/json

### 🔴 Test route inconnue (doit retourner 404)
GET {{baseUrl}}/nope

### ✅ Créer une catégorie
POST {{baseUrl}}/categories
Content-Type: {{json}}

{
  "libelle": "Tissu"
}

### ❌ Tester doublon catégorie (doit échouer)
POST {{baseUrl}}/categories
Content-Type: {{json}}

{
  "libelle": "Boisson"
}


### ❌ Libelle invalide
POST {{baseUrl}}/categories
Content-Type: {{json}}

{
  "libelle": "A"
}


### ✅ Voir toutes les catégories
GET {{baseUrl}}/categories


### ✅ Recherche catégorie
GET {{baseUrl}}/categories?search=Ti


### ✅ Voir catégorie par ID
GET {{baseUrl}}/categories/1


### ❌ Catégorie inexistante
GET {{baseUrl}}/categories/99


### ❌ ID invalide
GET {{baseUrl}}/categories/abc


### ✅ Supprimer catégorie
DELETE {{baseUrl}}/categories/3


### ❌ Supprimer catégorie inexistante
DELETE {{baseUrl}}/categories/2

### mettre a jour categorie
PUT  {{baseUrl}}/categories/1
Content-Type: {{json}}

{
  "libelle": "Nouveau chaussure"
}

### ✅ Créer un fournisseur
POST {{baseUrl}}/fournisseurs
Content-Type: {{json}}

{
  "prenom": "Awa",
  "nom": "Diop",
  "email": "ali@mail.com",
  "adresse": "Dakar",
  "telephone": "771034567"
}


### ❌ Téléphone déjà utilisé
POST {{baseUrl}}/fournisseurs
Content-Type: {{json}}

{
  "prenom": "Fatou",
  "nom": "Fall",
  "email": "fatfall@mail.com",
  "adresse": "Dakar",
  "telephone": "771434567"
}


### ❌ Fournisseur sans téléphone
POST {{baseUrl}}/fournisseurs
Content-Type: {{json}}

{
  "prenom": "Moussa",
  "nom": "Ndiaye",
  "email": "mss@mail.com",
  "adresse": "dakar"
}

### liste des fournisseurs
GET {{baseUrl}}/fournisseurs

### fournsseur par id
GET {{baseUrl}}/fournisseurs/1

### mettre a jour un fournisseur
PUT {{baseUrl}}/fournisseurs/1
Content-Type: {{json}}

{
  "prenom": "Awa Moussa",
  "nom": "Diop",
  "email": "awa.updated@gmail.com",
  "adresse": "Pikine",
  "telephone": "780000000"
}

### suprimer un fournisseur
DELETE {{baseUrl}}/fournisseurs/1

### rechercher un fournisseur
GET {{baseUrl}}/fournisseurs?search=awa

### ✅ Créer un produit (OK)
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Banane",
  "prixUnitaire": 500,
  "qteStock": 30,
  "dateExpiration": "2026-10-31",
  "categorieId": 1,
  "fournisseurId": 1
}

### vor tous les produits
GET {{baseUrl}}/produits

### ✅ Créer un produit (OK)
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Orange",
  "prixUnitaire": 500,
  "qteStock": 30,
  "dateExpiration": "2026-08-31",
  "categorieId": 1,
  "fournisseurId": 1
}

### ❌ Produit avec categorie inexistante
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Fanta",
  "prixUnitaire": 400,
  "qteStock": 5,
  "dateExpiration": "2026-12-31",
  "categorieId": 99,
  "fournisseurId": 1
}


### ❌ Produit avec fournisseur inexistant
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Pepsi",
  "prixUnitaire": 400,
  "qteStock": 5,
  "dateExpiration": "2026-12-31",
  "categorieId": 1,
  "fournisseurId": 99
}

### ❌ Produit avec prix invalide
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Sprite",
  "prixUnitaire": -100,
  "qteStock": 5,
  "dateExpiration": "2026-12-31",
  "categorieId": 1,
  "fournisseurId": 1
}


### ❌ Produit avec stock invalide
POST {{baseUrl}}/produits
Content-Type: {{json}}

{
  "libelle": "Oasis",
  "prixUnitaire": 300,
  "qteStock": -5,
  "dateExpiration": "2026-12-31",
  "categorieId": 1,
  "fournisseurId": 1
}

### mettre a jour un produit
PUT {{baseUrl}}/produits/1
Content-Type: {{json}}

{
  "libelle": "Riz 25kg",
  "prixUnitaire": 15000,
  "qteStock": 5,
  "dateExpiration": "2026-10-01",
  "categorieId": 1,
  "fournisseurId": 1
}

### suprimer un produit
DELETE {{baseUrl}}/produits/3